apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: registry.viettelidc.com.vn/private-repo-59e04ede-2f49-4678-99d7-cf90624091fb/myappbackend:v1.0.8
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/uploads"
              name: pvc
          resources: # ✅ Đúng: đặt bên trong container
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      imagePullSecrets:
        - name: idcregcred2
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: my-pvc
