api:
  image: ldd000/myappbackend:v1.2
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  pvc: my-pvc
  imagePullSecrets:
    - dockerhub-secret

ingress:
  enabled: true
  host: ducld12321.id.vn
  className: kong
  tlsSecret: app-tls-secret
