namespace: kong

api:
  image: ldd000/myappbackend:v1.2
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  pvc: my-pvc
  imagePullSecrets:
    - dockerhub-secret

service:
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: kong
  host: ducld12321.id.vn
  path: /backend
  pathType: Prefix
  tlsSecret: app-tls-secret
  service:
    name: api-service
    port: 80
  annotations:
    konghq.com/strip-path: "true"
