api:
  image: ldd0000/myappbackend:v3.0.0
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  pvc: my-pvc
  imagePullSecrets:
    - idcregcred2
ingress:
  host: ducld12321.id.vn
  className: nginx-class
  tlsSecret: app-tls-secret
