apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: kong
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image }}
          ports:
            - containerPort: 5000
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
            - name: pvc
              mountPath: /uploads
          imagePullPolicy: Always
      imagePullSecrets:
        {{- range .Values.api.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: {{ .Values.api.pvc }}