apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.selector.app }}
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: {{ .Values.api.container.name }}
          image: {{ .Values.api.image }}
          ports:
            - containerPort: {{ .Values.api.container.port }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
            - name: pvc
              mountPath: /uploads
          imagePullPolicy: Always
      imagePullSecrets:
        {{- range .Values.api.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: {{ .Values.api.pvc }}