{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-to-api-service-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: {{ .Values.api.ingress.className | quote }}
  {{- if .Values.api.ingress.tlsSecret }}
  tls:
    - hosts:
        - {{ .Values.api.ingress.host }}
      secretName: {{ .Values.api.ingress.tlsSecret }}
  {{- end }}
  rules:
    - host: {{ .Values.api.ingress.host }}
      http:
        paths:
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 80
{{- end }}
